"""Add assigned_model to AgentModel

Revision ID: 1f8e44e8d949
Revises: 
Create Date: 2024-10-06 09:49:54.767580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8e44e8d949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_model', schema=None) as batch_op:
        batch_op.drop_column('assigned_model')

    # ### end Alembic commands ###
