"""Add version and is_active to Prompt model

Revision ID: d94db61773b7
Revises: 1f8e44e8d949
Create Date: 2024-10-06 09:56:22.472307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94db61773b7'
down_revision = '1f8e44e8d949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('version')

    # ### end Alembic commands ###
